export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_LOGOUT='AUTH_LOGOUT';

export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAIL = 'GET_USER_FAIL';

export const SET_PLAYLIST='SET_PLAYLIST';

export const SET_TRACKS="SET_TRACKS";
export const SET_TRACKS_FAIL="SET_TRACKS_FAIL"

export const SET_NEW_RELEASES='SET_NEW_RELEASES'
export const SET_NEW_RELEASES_FAIL='SET_NEW_RELEASES_FAIL'
export const SET_CATEGORIES='SET_CATEGORIES'
export const SET_FEATURED='SET_FEATURED'